### PR TITLE
Quote URLs

### PR DESCRIPTION
**Pull request by jaytaylor**
Quote URLs to allow pasting to terminals without &params forking processes.

### CODE REVIEW

**Comment by moul** [comment]
LGTM

**Comment by QuentinPerez** [comment]
LGTM

**Comment by moul** [comment]
Thanks @jaytaylor !

**Comment by jaytaylor** [comment]
Wow, that was quick! Thanks @moul for the new record merge time, you just made my day and blew me away! :::)))

**Pull request merged**
